# Generated by Django 5.1.3 on 2025-05-15 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('employee', 'Employee')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=20)),
                ('college_name', models.CharField(blank=True, max_length=255, null=True)),
                ('college_id', models.CharField(blank=True, max_length=255, null=True)),
                ('government_id', models.CharField(max_length=255)),
                ('verification_status', models.CharField(default='pending', max_length=20)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('college_id_photo', models.FileField(upload_to='uploads/')),
                ('gov_id_photo', models.FileField(upload_to='uploads/')),
                ('selfie', models.ImageField(upload_to='uploads/')),
                ('ssc_certificate', models.FileField(upload_to='uploads/')),
                ('graduate_certificate', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('college_id_name_extracted', models.CharField(blank=True, max_length=255, null=True)),
                ('college_id_num_extracted', models.CharField(blank=True, max_length=255, null=True)),
                ('gov_name_extracted', models.CharField(blank=True, max_length=255, null=True)),
                ('gov_id_extracted', models.CharField(blank=True, max_length=255, null=True)),
                ('gov_dob_extracted', models.CharField(blank=True, max_length=50, null=True)),
                ('ssc_name_extracted', models.CharField(blank=True, max_length=255, null=True)),
                ('ssc_dob_extracted', models.CharField(blank=True, max_length=50, null=True)),
                ('grad_name_extracted', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
